checkseries<-function(ns,button_style2){
  column(1,align = "left",
         br(),
         br(),
         br(),
         br(),
         checkboxInput(ns('1_1'), NULL, FALSE),
         br(),
         checkboxInput(ns('1_2'), NULL, FALSE),
         br(),
         checkboxInput(ns('1_3'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('1_4'), NULL, FALSE),
         br(),
         checkboxInput(ns('1_5'), NULL, FALSE),
         br(),
         checkboxInput(ns('1_6'), NULL, FALSE),
         br(),
         br(),# start of the 2. Perform
         br(),
         br(),
         br(),
         br(),
         checkboxInput(ns('2_1'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('2_2'), NULL, FALSE),
         br(),
         checkboxInput(ns('2_3'), NULL, FALSE),
         br(),
         checkboxInput(ns('2_4'), NULL, FALSE),
         br(),
         checkboxInput(ns('2_5'), NULL, FALSE),
         br(),
         checkboxInput(ns('2_6'), NULL, FALSE),
         br(),
         br(),#start of 3. Identify aternative (MNA)
         br(),
         br(),
         br(),
         checkboxInput(ns('3_1a'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_2a'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('3_3a'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('3_4a'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_5a'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_6a'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_7a'), NULL, FALSE),
         br(),
         br(),
         br(),
         br(),
         checkboxInput(ns('3_1b'), NULL, FALSE), # if pump and treat
         br(),
         checkboxInput(ns('3_2b'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_3b'), NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput(ns('3_4b'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_5b'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_6b'), NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput(ns('3_7b'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_8b'), NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput(ns('3_9b'), NULL, FALSE),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         checkboxInput(ns('3_1c'), NULL, FALSE),# if a pump and treat
         br(),
         checkboxInput(ns('3_2c'), NULL, FALSE),
         br(),
         checkboxInput(ns('3_3c'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('3_4c'), NULL, FALSE),
         br(),
         br(),#3. idenfity (enhanced/active)
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         checkboxInput(ns('4_1a'), NULL, FALSE),
         br(),
         checkboxInput(ns('4_2a'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('4_3a'), NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput(ns('4_4a'), NULL, FALSE),
         br(),
         br(),
         br(),
         br(),
         checkboxInput(ns('4_1b'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('4_2b'), NULL, FALSE),
         br(),
         checkboxInput(ns('4_3b'), NULL, FALSE),
         br(),
         checkboxInput(ns('4_4b'), NULL, FALSE),
         br(),# 3. identify (MNA continued)
         br(),
         br(),
         br(),
         HTML("<h3> </h3>"),
         HTML("<h4> </h4>"),
         HTML("<h4> </h4>"),
         br(),
         br(),
         checkboxInput(ns('5_1'), NULL, FALSE),
         br(),
         br(),
         checkboxInput(ns('5_2'), NULL, FALSE),
         br(),
         checkboxInput(ns('5_3'), NULL, FALSE),
         br(),
         checkboxInput(ns('5_4'), NULL, FALSE),
         br(),
         br(),
         br()
         
  )
  
}