checkseries<-function(ns,button_style2){
  column(1,align = "left",
         br(),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),# start of the 2. Perform
         br(),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),#start of 3. Identify aternative (MNA)
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE), # if pump and treat
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),# if a pump and treat
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),#3. idenfity (enhanced/active)
         br(),
         br(),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),# 3. identify (MNA continued)
         br(),
         br(),
         br(),
         HTML("<h3> </h3>"),
         HTML("<h4> </h4>"),
         HTML("<h4> </h4>"),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),# 3. identify (EA)
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         br(),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE),
         br(),
         checkboxInput('header', NULL, FALSE)   
         
  )
  
}