helpseries<-function(ns,button_style2){
  column(1,align = "left",
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),# start of the 2. Perform
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),#start of 3. Identify alternative (MNA)
         HTML("<h4> </h4>"),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         br(),
         HTML("<h2> </h2>"),
         actionButton(ns("help1"), HTML("?"), style = button_style2), # if pump and treat
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),# if a pump and treat
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),#4. idenfity (enhanced/active)
         br(),
         br(),
         br(),
         br(),
         HTML("<h2> </h2>"),
         #actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         HTML("<h2> </h2>"),
         #actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),# 5. identify (MNA continued)
         br(),
         br(),
         br(),
         br(),

         #actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),# 6. identify (EA)
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2)     
                  
  )
  
}