helpseries<-function(ns,button_style2){
  column(1,align = "left",
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd2"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd3"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd4"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd5"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd6"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),# start of the 2. Perform
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd7"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd8"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd9"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd10"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd10"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd12"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),#start of 3. Identify alternative (MNA)
         HTML("<h4> </h4>"),
         br(),
         br(),
         br(),
         actionButton(ns("helpd13"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd14"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd15"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd16"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd17"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd18"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd19"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         br(),
         HTML("<h2> </h2>"),
         actionButton(ns("helpd20"), HTML("?"), style = button_style2), # if pump and treat
         br(),
         br(),
         actionButton(ns("helpd21"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd22"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd23"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd24"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd25"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd26"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd27"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd28"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd29"), HTML("?"), style = button_style2),# if a pump and treat
         br(),
         br(),
         actionButton(ns("helpd30"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd31"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd32"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),#4. idenfity (enhanced/active)
         br(),
         br(),
         br(),
         br(),
         HTML("<h2> </h2>"),
         #actionButton(ns("helpd1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd33"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd34"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd35"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("helpd36"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         HTML("<h2> </h2>"),
         #actionButton(ns("helpd1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd37"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd38"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd39"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd40"), HTML("?"), style = button_style2),
         br(),# 5. identify (MNA continued)
         br(),
         actionButton(ns("helpd41"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd42"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd43"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd44"), HTML("?"), style = button_style2),
         br(),# 5. identify (MNA continued)
         br(),
         actionButton(ns("helpd45"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("helpd46"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("helpd47"), HTML("?"), style = button_style2),
         br()
 
                  
  )
  
}