helpseries<-function(ns,button_style2){
  column(1,align = "left",
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),# start of the 2. Perform
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),#start of 3. Identify aternative (MNA)
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2), # if pump and treat
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),# if a pump and treat
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),#3. idenfity (enhanced/active)
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),# 3. identify (MNA continued)
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),# 3. identify (EA)
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2),
         br(),
         br(),
         actionButton(ns("help1"), HTML("?"), style = button_style2)     
                  
  )
  
}